services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

    ports:
      - "5442:5432"

  mcp-server:
    image: mcp-server-expense-tracker
    ports:
      - "8009:8009"
    volumes:
    - ./expense_data:/app/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: app
    command: uv run streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - backend
    ports:
      - "8501:8501"
    env_file:
      - .env
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: uv run uvicorn src.routes:app --host 0.0.0.0 --port 8005
    ports:
      - "8005:8005"
    depends_on:
      - postgres
      - mcp-server
    volumes:
      - ./images:/app/images
    env_file:
      - .env
volumes:
  pgdata:
  ollama_data:
    external: true