FROM python:3.11

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen

COPY . .

EXPOSE 8005

CMD ["uv", "run", "uvicorn", "src.routes:app", "--host", "0.0.0.0", "--port", "8005"]